In [1]:
import os
import sys
import matplotlib.pyplot as plt
from scipy.signal import argrelextrema
import numpy as np

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)
    
from data_handle import(
    ForexDataClean,
    ForexDataLoad,
)

from features import ForexFeauturesExtractor

from plots import ForexPlotter

import warnings
warnings.filterwarnings('ignore')

data = ForexDataLoad(file_path = '../data/xauaud.csv').data

cleaner = ForexDataClean(data = data)
data = cleaner.fast_cleaner()

features = ForexFeauturesExtractor(
    data = data
)

# all_features, indicators_data, signals_data, extreme_data = features.extract_all_features()

==================================================
FOREX DATA LOADER
==================================================
 Available Fuctions
1 load_csv
2 load_from_database
==================================================
Data loaded successfully!
Shape: (38217, 5)

==================================================
==================================================
FOREX DATA CLEANER
==================================================
 Available Fuctions
1 remove_duplicates
2 handle_missing_values
3 validate_ohlc_integrity
4 handle_outliers
5 fast_cleaner
==================================================
==================================================
Keep = first and subset = None
Removed 0 duplicate entries
==================================================
OHLC DATA INTEGRITY VALIDATION
==================================================
No OHLC integrity violations found
All OHLC values are consistent
Found 1 missing values
 dropped: 1 missing values .
==================================================
OHLC DATA INTEGRITY VALIDATION
==================================================
No OHLC integrity violations found
All OHLC values are consistent

In [2]:
import pandas as pd

In [3]:
from features import ForexCCISignals, ForexMomentumIndicators

In [4]:
momentum = ForexMomentumIndicators(data = data).generate_all_momentum_indicators()

==================================================
MOMENTUM INDICATORS
==================================================
 Available Fuctions
1 add_rsi
2 add_stochastic
3 add_williams_r
4 add_cci
5 add_momentum
6 generate_all_momentum_indicators
==================================================
==================================================
Data Info
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38216 entries, 2017-04-24 02:00:00 to 2025-09-05 20:00:00
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   close                38216 non-null  float64
 1   rsi_14               38202 non-null  float64
 2   rsi_14_slope         38201 non-null  float64
 3   rsi_21               38195 non-null  float64
 4   rsi_21_slope         38194 non-null  float64
 5   rsi_28               38188 non-null  float64
 6   rsi_28_slope         38187 non-null  float64
 7   stoch_slowk_3        38199 non-null  float64
 8   stoch_slowd_3        38199 non-null  float64
 9   stoch_slowk_3_slope  38198 non-null  float64
 10  stoch_slowd_3_slope  38198 non-null  float64
 11  williams_r_14        38203 non-null  float64
 12  williams_r_14_slope  38202 non-null  float64
 13  williams_r_21        38196 non-null  float64
 14  williams_r_21_slope  38195 non-null  float64
 15  williams_r_28        38189 non-null  float64
 16  williams_r_28_slope  38188 non-null  float64
 17  cci_14               38203 non-null  float64
 18  cci_14_slope         38202 non-null  float64
 19  cci_21               38196 non-null  float64
 20  cci_21_slope         38195 non-null  float64
 21  cci_28               38189 non-null  float64
 22  cci_28_slope         38188 non-null  float64
 23  momentum_10          38206 non-null  float64
 24  momentum_10_slope    38205 non-null  float64
 25  momentum_14          38202 non-null  float64
 26  momentum_14_slope    38201 non-null  float64
 27  momentum_20          38196 non-null  float64
 28  momentum_20_slope    38195 non-null  float64
dtypes: float64(29)
memory usage: 8.7 MB
None
==================================================
Shape of data (38216, 29)
==================================================
0 rows removed
==================================================

In [5]:
cci_signals = ForexCCISignals(
    data = momentum[0],
    parameters = momentum[1]['cci_params']
).generate_all_cci_signals()

==================================================
CCI SIGNAL GENERATION
==================================================
Available functions:
1 cci_overbought_oversold_signals
2 cci_momentum_signals
3 cci_reversal_signals
4 cci_divergence_signals
5 cci_zero_line_signals
6 generate_all_cci_signals
==================================================
[14, 21, 28]
['cci_14', 'cci_21', 'cci_28']
['cci_14_slope', 'cci_21_slope', 'cci_28_slope']
cci_14
cci_21
cci_28
==================================================
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38216 entries, 2017-04-24 02:00:00 to 2025-09-05 20:00:00
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   close                       38216 non-null  float64
 1   cci_14_overbought_oversold  38216 non-null  int64
 2   cci_21_overbought_oversold  38216 non-null  int64
 3   cci_28_overbought_oversold  38216 non-null  int64
 4   cci_14_extreme              38216 non-null  int64
 5   cci_21_extreme              38216 non-null  int64
 6   cci_28_extreme              38216 non-null  int64
dtypes: float64(1), int64(6)
memory usage: 2.3 MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38216 entries, 2017-04-24 02:00:00 to 2025-09-05 20:00:00
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   close                  38216 non-null  float64
 1   cci_14_slope_momentum  38216 non-null  int64
 2   cci_21_slope_momentum  38216 non-null  int64
 3   cci_28_slope_momentum  38216 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 1.5 MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38216 entries, 2017-04-24 02:00:00 to 2025-09-05 20:00:00
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   close            38216 non-null  float64
 1   cci_14_reversal  38216 non-null  int64
 2   cci_21_reversal  38216 non-null  int64
 3   cci_28_reversal  38216 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 1.5 MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38216 entries, 2017-04-24 02:00:00 to 2025-09-05 20:00:00
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   close              38216 non-null  float64
 1   cci_14_divergence  38216 non-null  int64
 2   cci_21_divergence  38216 non-null  int64
 3   cci_28_divergence  38216 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 1.5 MB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38216 entries, 2017-04-24 02:00:00 to 2025-09-05 20:00:00
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   close              38216 non-null  float64
 1   cci_14_zero_cross  38216 non-null  int64
 2   cci_21_zero_cross  38216 non-null  int64
 3   cci_28_zero_cross  38216 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 1.5 MB
None
==================================================
Shape of overbought_oversold_data (38216, 7)
Shape of momentum_data (38216, 4)
Shape of reversal_overbought_oversold_data (38216, 4)
Shape of divergence_data (38216, 4)
Shape of zero_cross_data (38216, 4)
==================================================
0 rows removed
==================================================

In [7]:
cci_signals['zero_cross']

,close,cci_14_zero_cross,cci_21_zero_cross,cci_28_zero_cross
datetime,,,,
2017-04-24 02:00:00,1682.15,0,0,0
2017-04-24 03:00:00,1689.13,0,0,0
2017-04-24 04:00:00,1687.68,0,0,0
2017-04-24 05:00:00,1688.36,0,0,0
2017-04-24 06:00:00,1687.06,0,0,0
...,...,...,...,...
2025-09-05 16:00:00,5455.01,0,0,0
2025-09-05 17:00:00,5474.64,0,0,0
2025-09-05 18:00:00,5468.49,0,0,0
2025-09-05 19:00:00,5476.84,0,0,0
2025-09-05 20:00:00,5477.23,0,0,0